#!/bin/sh
set -eu

ID="$1"
NET="$2"

dir="/run/sb/${ID}"
mkdir -p "${dir}/attached"

unshare -n sleep infinity &
pid="$!"

echo "${pid}" >"${dir}/pid"
nsenter -t "${pid}" -n ip link set lo up
CNI_ARGS="IgnoreUnknown=1;K8S_POD_NAME=${ID}"
export CNI_ARGS
cnitool add "${NET}" "/proc/${pid}/ns/net" >"${dir}/attached/${NET}"

# return the result
ns="/proc/${pid}/ns/net"
dns="$(jq -r ".dns.nameservers[0]" < "${dir}/attached/${NET}")"
echo "{\"ns\":\"${ns}\",\"dns\":\"${dns}\"}"
