#!/bin/sh
set -eux

ID=$1
NET=$2

dir="/run/sb/${ID}"
if [ ! -f "${dir}/pid" ]; then
	exit 0
fi
pid=$(cat "${dir}/pid")
cnitool del "${NET}" "/proc/${pid}/ns/net"
rm -f "${dir}/attached/${NET}"

nwcount=$(find "${dir}/attached" -type f | wc -l)
if [ -z "${nwcount}" ]; then
	kill -9 "${pid}"
	rm -rf "${dir}"
fi
